update

diff --git a/dot-scripts/common-backup-brave b/dot-scripts/common-backup-brave
--- a/dot-scripts/common-backup-brave
+++ b/dot-scripts/common-backup-brave
@@ -1,27 +1,30 @@
 #!/bin/bash
 
-catch() { echo "${1}"; exit 1; }
-
-echo "Backing up Brave"
-
 brave_dir="${HOME}/.config/BraveSoftware"
-[[ -d "${brave_dir}" ]] \
-|| catch "Path not found: '${brave_dir}'"
+if [[ ! -d "${brave_dir}" ]]; then
+    echo "Path not found: '${brave_dir}'"
+    exit 1
+fi
 
 backup_drive="$(lsblk -no mountpoints | grep -si "/STUFF"$ || true)"
-[[ -d "${backup_drive}" ]] \
-|| catch "Path not found: '${backup_drive}'"
+if [[ ! -d "${backup_drive}" ]]; then
+    echo "Path not found: '${backup_drive}'"
+    exit 1
+fi
 
 backup_name="BraveSoftware-$(printf "%(%Y-%m-%d)T\n" -1)"
 backup_path_base="${backup_drive}/linux"
-mkdir -p "${backup_path_base}" \
-|| catch "Failed to create '${backup_path_base}'"
+mkdir -p "${backup_path_base}"
 backup_path="${backup_path_base}/${backup_name}"
 
-[[ ! -f "${backup_path}" ]] \
-|| catch "Backup exists: '${backup_path}'"
-
-tar -czvf "${backup_path}" "${brave_dir}" \
-|| catch "Failed to create backup: '${backup_path}'"
-
-echo "Backup complete."
+if [[ -f "${backup_path}" ]]; then
+    echo "Backup already exists: '${backup_path}'"
+    exit 0
+else
+    if tar -czvf "${backup_path}" "${brave_dir}"; then
+        echo "Backup created: '${backup_path}'"
+    else
+        echo "Failed to create backup: '${backup_path}'"
+        exit 1
+    fi
+fi
