update
Co-authored-by: Copilot <copilot@github.com>

diff --git a/dot-scripts/common-rename-walls b/dot-scripts/common-rename-walls
--- a/dot-scripts/common-rename-walls
+++ b/dot-scripts/common-rename-walls
@@ -2,30 +2,25 @@
 
 catch() { echo "${1}"; exit 1; }
 
-for cmd in convert openssl; do
-    command -v "${cmd}" 1>/dev/null \
-    || catch "Command not found: '${cmd}'"
-done
+command -v convert 1>/dev/null || not_found+=(convert)
+command -v openssl 1>/dev/null || not_found+=(openssl)
+[[ "${#not_found[@]}" = 0 ]] || { printf "Command not found: '%s'\n" "${not_found[@]}"; exit 1; }
 
 walls_dir="${HOME}/dotfiles/dot-walls"
 walls=("${walls_dir}"/*.jpg "${walls_dir}"/*.jpeg "${walls_dir}"/*.png)
-(( ${#walls[@]} > 0 )) \
-|| catch "No files found in '${walls_dir}' directory."
+(( ${#walls[@]} > 0 )) catch "No files found in '${walls_dir}' directory."
 
 for wall in "${walls[@]}"; do
     random_hex=$(openssl rand -hex 4 || true)
-    [[ -n "${random_hex}" ]] \
-    || catch "Failed to generate random hex string for ${wall}."
+    [[ -n "${random_hex}" ]] || catch "Failed to generate random hex string for ${wall}."
     ext="${wall##*.}"
     new_file_name="${walls_dir}/${random_hex,,}.jpg"
-    if [[ "${ext}" == "png" ]]; then
-        echo "${wall##*/} -> ${new_file_name}"
-        convert "${wall}" -quality 100 "${new_file_name}" \
-        || catch "Failed to convert ${wall} to JPEG format."
-        rm -f "${wall}" \
-        || catch "Failed to remove original file ${wall}."
-    fi
+    
     echo "${wall##*/} -> ${new_file_name}"
-    mv -n "${wall}" "${new_file_name}" \
-    || catch "Failed to rename ${wall} to ${new_file_name}."
+    if [[ "${ext}" == "png" ]]; then
+        convert "${wall}" -quality 100 "${new_file_name}" || catch "Failed to convert ${wall} to JPEG format."
+        rm -f "${wall}" || catch "Failed to remove original file ${wall}."
+    else
+        mv -n "${wall}" "${new_file_name}" || catch "Failed to rename ${wall} to ${new_file_name}."
+    fi
 done
