update

diff --git a/dot-scripts/hyrule-aur-update b/dot-scripts/hyrule-aur-update
--- a/dot-scripts/hyrule-aur-update
+++ b/dot-scripts/hyrule-aur-update
@@ -1,14 +1,13 @@
 #!/bin/bash
 
-catch() { echo "${1}"; exit 1; }
+if ! command -v yay 1>/dev/null; then
+    echo "Install 'yay'"
+    exit 1
+fi
 
-for cmd in pacman yay; do
-    command -v "${cmd}" 1>/dev/null \
-    || catch "Command not found: '${cmd}'"
-done
+if ! ping -qn -c 1 aur.archlinux.org &> /dev/null; then
+    echo  "Cannot ping AUR"
+    exit 1
+fi
 
-ping -qn -c 1 aur.archlinux.org &> /dev/null \
-|| catch "Cannot ping AUR"
-
-yay -Sua --noconfirm --cleanafter --ignore gcc14 --ignore gcc14-libs \
-|| catch "Failed to update AUR packages"
+yay -Sua --noconfirm --cleanafter --ignore gcc14 --ignore gcc14-libs
